# Should return correct user with specified id
# If user doesn't exist, 404 will be returned (example below)
GET http://localhost:9080/blog/api/users/1
Accept: application/json

###

# Should return 404 - initial data consists of 4 users with id 1-4
GET http://localhost:9080/blog/api/users/5
Accept: application/json

###

# Should return list of users
GET http://localhost:9080/blog/api/users
Accept: application/json

###